amanmehara/programming

- PYTHON/Sending SMS/SendingSms.py
#1 add simple sending sms script
> add sending sms script using python

- PYTHON/Neural Net/neural_net.py
A simple neural network implementation from scratch in python
> Add 1 Project : Neural net from scratch in Python

- PYTHON/While Statement/whileStatement.py
> Add 1 project

- C/SPOJsolutions/spoj_bottomcoder_easy.c
> Added solved SPOJ problems in C

- PYTHON/Factorial/Factorial.py
- PYTHON/Recursion (Factorial)/RecursiveFactorial.py
Added python programs for calculating factorial with and without recursion.
> Add 2 Projects

- PYTHON/WorkingWithList/AccessListElement
- PYTHON/WorkingWithList/AccessListElement.py
- PYTHON/WorkingWithList/SlicingList
- PYTHON/WorkingWithList/SlicingList.py
added two programs on list in Python
> added two python programs

- C++/optimization/The Traveling Postman Problem/README
- C++/optimization/The Traveling Postman Problem/main.cpp
- C++/optimization/The Traveling Postman Problem/point.h
- C++/optimization/The Traveling Postman Problem/the_traveling_postman_problem.cpp
- C++/optimization/The Traveling Postman Problem/the_traveling_postman_problem.h
Here goes the codes to solve the Traveling Postman Problem with Dynamic Programming.
> The Traveling Postman Problem

- Go/BinarySearch.go
Implemented code for Binary Search in go language.
> [Go] Binary Search

- C++/search/linear_search.cpp
Restored the binary search implementation "search.h"
> [C++] Linear Search

- C++/trie/auto complete.cpp
**Auto-Complete**
_Problem Statement:_ 
Given **n** number of words and an incomplete word **w**. We need to auto-complete that word **w**.
Printing all the possible words which can be formed using the incomplete word **w**.
Sample Test Case:
_Input:_
7
do dont no not note notes den
no
_Output:_
no
not
note
notes
_Solution approach_:
-  Insert all the **n** words in a trie and also mark the terminal nodes.
-  Check if the given pattern exist in the trie or not, if it doesn't then return, else store the address of the ending node of the pattern in the trie.
- Now our task is to find all the root to leaf path words( here root will the address that we obtained from the previous step) and append it to the pattern.  
_Testing_:  Tested locally and also in online IDE.
_Result_:  Code is working …
> [C++] Autocomplete using Trie Data Structure

- Go/LinearSearch.go
Implemented code for Linear Search in go language.
> [Go] Linear Search

- C/Bankers Algorithm/bankersAlgorithm.c
I have added the file for Banker's algorithm and made sure that they satisfy the guidelines given. Kindly label this pull request with 'hacktoberfest' label.
> [C] Banker's Algorithm

- Python/Algorithms/Dijkstras.py
- Python/Algorithms/quicksort.py
added dijkstars shortest path finding algorithm using python
> [Python] Dijkstra's Algorithm & Quick Sort

- Python/ScrappingHackerNewsWebsite/README.md
- Python/ScrappingHackerNewsWebsite/ScrappingHackerNewsWebsite.py
Issue no- #40 
About PR: This script is used to scrap the first 2 pages of hacker news website and gives only the stories with links which have upvotes more than 100. Please assign this PR for 'Hacktoberfest'
> [Python] Website Scraping (Using Requests & Beautiful Soup)

- Java/Binary Tree BFS Traversal/BinaryTreeBFS.java
Added Solution for BFS traversal of a binary tree in java's folder
> [Java] Binary Tree Traversal (Breadth First)

- Python/Algorithms/tower_of_hanoi.py
Added implementation of Tower of Hanoi algorithm, with minimum number of moves.
I've followed the naming conventions of [your implementation of this algorithm in C](https://github.com/amanmehara/programming/blob/master/C/Recursion%20(tower%20of%20hanoi)/towerOfHanoi.c), using snake case.
I put the `.py` file in the `Algorithms/` folder, but maybe it can be put in a `Recursive/` folder!
> [Python] Tower of Hanoi

- Go/Bubble Sort/bubble_sort.go
Add bubble sort algorithm implementation using Go
> [Go] Bubble Sort

- Go/Merge Sort/merge_sort.go
> [Go] Merge Sort

- Go/Selection Sort/selection_sort.go
Add selection sort algorithm implementation using Go
> [Go] Selection Sort

- Java/Binary Tree Views/BinaryNode.java
- Java/Binary Tree Views/BinaryTreeBottomView.java
- Java/Binary Tree Views/BinaryTreeLeftView.java
- Java/Binary Tree Views/BinaryTreeRightView.java
- Java/Binary Tree Views/BinaryTreeTopView.java
Added Solution for binary tree views(top,bottom,left,right) in java
> [Java] Binary Tree Views

- C/Infix to Postix Conversion/infix-to-postfix.c
Infix to Post fix expression  written in c.
> [C] Infix to Postfix (Expression Transformation)

- Ruby/For Statement/forRange.rb
- Ruby/For Statement/forStatement.rb
This establishes ports of the For Statement for the Ruby programming language. These implementations replicate the behavior established in the Python contributions.
> [Ruby] For & Range

- Ruby/Minimal Class/minimal_class.rb
This replicates the Python minimal class implementation for the Ruby programming language.
> [Ruby] Minimal Class

- Ruby/If Statement/if-statement-conditionals.rb
This adds the first code implementation for the Ruby programming language.
> [Ruby] if elsif else

- Go/QuickSort.go
Implemented code for Quick Sort in Go language.
> [Go] Quick Sort

- Go/InsertionSort.go
Implemented code for Insertion Sort in Go language.
> [Go] Insertion Sort

- Python/Algorithms/selection.py
> [Python] Selection Sort

- Python/Algorithms/Gradient_descent.py
Implemented Gradient Descent using numpy , used sklearn for creating regression datasets
> [Python] Gradient Descent

- JavaScript/Quick Sort/QuickSort.js
Adds Javascript implementation of Quick Sort.
> [JavaScript] Quick Sort

- C++/sort/MergeTwoSortedArray.cpp
Time Complexity O(m+n) i.e O(n)
input: 
f[]={11,16,21,45}
s[]={6,8,8,11,16}
output:
6 8 8 11 11 16 16 21 45
> [C++] Sort (Merge 2 Sorted Array)

- Python/Algorithms/interpolation search.py
This search algorithm works on the probing position of the required value.
> [Python] Interpolation Search

- Python/Algorithms/shellsort.py
Shell Sort involves sorting elements which are away from each other
> [Python] Shellsort

- Python/Sending Emails With Python/emails.py
Issue with Implementations in Python #40
> [Python] Sending E-mail

- Python/Algorithms/Huffman_Coding.py
I am a beginner and I want to participate in hacktoberfest .So I have generated this Pr. This algorithm was not there in this repo.
> [Python] Huffman Coding

- Ruby/Arrays/array.rb
- Ruby/For Statement/times.rb
- Ruby/Hashes/hash.rb
- Ruby/Unless Statement/unless.rb
Added .rb files for the following concepts
1. Array
2. Hash
3. Times keyword
4. Unless keyword
> [Ruby] unless, hash, times & Arrays

- C++/competitive/GoogleKickstart/2020/Round A/allocation.cpp
- C++/competitive/GoogleKickstart/2020/Round A/plates.cpp
- C++/competitive/GoogleKickstart/2020/Round A/workout.cpp
- C++/competitive/GoogleKickstart/2020/Round E/LongestArithmetic.cpp
I added solved Google Kickstart problems in competitive folder in C++. Here you will find solutions to 4 problems, 3 from round A 2020 and 1 from round E 2020.
> [C++] Competitive (Kick Start)

- CONTRIBUTING.md
- Python/Recursion (Algorithms)/binary_search.py
i've implemented a binary search using recursion, do have a look!
> [Python] Recursive Binary Search

- C/Algorithm to add 2 big numbers/add2numbers.c
Using this algorithm we can add two positive integers which won't fit even in unsigned long long int datatype.
For example - 
Input:
1983479127394712739417293471297349712347812 12938471297349127394791273497123471297341927
Output:
14921950424743840134208566968420821009689739
> [C] Add 2 Big Integers

- C++/language/RecursionSumofDig.cpp
by using recursion printing sum of digits.
input=253
output:
sum of digit=10
input=2323
output:
sum of digit=10
> [C++] Sum of Digits (Recursion)

- JavaScript/String/checkNumOfConsonants.js
- JavaScript/String/checkNumOfVowels.js
- JavaScript/number/factorial.js
- JavaScript/number/findAbsolute.js
- JavaScript/recursion/factorial.js
> [JavaScript] Number & String

- Go/Queue/queue.go
added Queue realization on Golang language
> [Go] Queue

- C++/competitive/LeetCode/reverse_nodes_in_k_group.cpp
Added code for Leetcode problem "Reverse Nodes in k-Group" in C++ | Competitive Programming.
> [C++] Competitive (LeetCode)

- Java/Swap/SwapWithoutTempVariable.java
I have added program to swap two variables without using temp variable.
> [Java] Swap without using Temporary Variable

- Python/Algorithms/insertion_sort.py
I have completed program to sort elements of array using insertion sort.
> [Python] Insertion Sort

- C/Command Simulation (deluser)/deluser.c
The following code written in C simulates the deluser command.
> [C] Simulation (deluser)

- C/Stable Matching/Stable_Matching.c
added stable matching code in C
> [C] Stable Matching

- Java/EuclideanAlgo/EuclideanAlgo.java
I have completed program to find gcd of two numbers using euclidean algorithm.
> [Java] Euclidean Algorithm (GCD)

- Java/FloydCycleDetectionAlgo/FloydCycleDetectionAlgo.java
I have completed program to detect cycles using Floyd's cycle detection algorithm.
> [Java] Floyd's Cycle Detection Algorithm

- Java/SieveOfEratosthenes/SieveOfEratosthenes.java
I have completed program to find prime numbers upto a certain number using sieve of eratosthenes algorithm.
> [Java] Sieve of Eratosthenes

- Python/Algorithms/SieveOfEratosthenes.py
I have create program to find prime numbers using sieve of eratosthenes algorithm.
> [Python] Sieve of Eratosthenes
